### ISSUE TITLE
Does this still require a daemon?

### ISSUE THREAD

**Issue by mikeal** [ipfs-shipyard/ipfs-blob-store#15]
I saw this note:

> ipfs-blob-store today requires a running IPFS daemon to talk to over HTTP. This module will be able to be entirely self-contained once js-ipfs is complete.

However, js-ipfs looks like it now has feature parity so is this still true?

**Comment by noffle** [comment]
I believe this is still true today, because we're still converging on a single interface that lets you use js-ipfs or the HTTP API to a remote daemon.

*Very* soon it'll all be behind [interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core/), so you can swap between the two indiscriminately.

**Comment by hacdias** [comment]
I think this question was answered, @diasdavid

**Comment by diasdavid** [comment]
It should not. @achingbrain implemented mfs for js-ipfs now too :D
